### ISSUE TITLE
[Features module] Fix failed tests and improve code/coverage

### ISSUE THREAD

**Issue by FarnazH** [theochem/Selector#126]
**Critically** review the code in [features module](https://github.com/theochem/DiverseSelector/blob/main/DiverseSelector/features.py), update docstrings, add tests and comments to the code to make it more clear. Fix tests that are failing in `DiverseSelector/test/test_feature.py`.

For example, the [`feature_reader`](https://github.com/theochem/DiverseSelector/blob/main/DiverseSelector/features.py#LL439C5-L439C19) seems redundant to me. It is just 2 lines of actual code (but we need a lot of likes to explain/document the function), and we can show how to load the data file in an example/notebook or expect the user to know about it. In a nutshell, I don't think making a wrapper function for every functionality from other packages is helpful/useful. It is best (and to our advantage) to show how our package works in conjunction with other packages (in this case `pandas`). Feel free to let me know what you think @FanwangM and @PaulWAyers.

**Comment by maximilianvz** [comment]
I believe the tests related to the [modred_desc](https://github.com/theochem/DiverseSelector/blob/7be2723c51f757912b61e59a08ca6379361751dd/DiverseSelector/features.py#LL57C86-L57C86) function (i.e., [test_feature_desc_mordred_2d](https://github.com/theochem/DiverseSelector/blob/7be2723c51f757912b61e59a08ca6379361751dd/DiverseSelector/test/test_feature.py#L43) and [test_feature_desc_mordred_3d](https://github.com/theochem/DiverseSelector/blob/7be2723c51f757912b61e59a08ca6379361751dd/DiverseSelector/test/test_feature.py#LL64C2-L64C2)) were failing due to the [removal of a feature from the networkx package](https://stackoverflow.com/questions/61154740/attributeerror-module-networkx-has-no-attribute-connected-component-subgraph).

I previously had version 2.8.8 of networkx installed in a conda environment, and these two tests were failing. I did `pip install --force-reinstall networkx==2.3` (the required feature was removed in version 2.4), and then the tests passed. @FarnazH, it would be worth you trying this fix to see if it is indeed correct.

**Comment by maximilianvz** [comment]
I've just realized that each of us may have different environments configured for running tests. If that is true, there is a chance that different tests pass/fail for us. As it currently stands, this is the state of the tests for me:

<img width="1917" alt="Screenshot 2023-06-07 at 1 12 55 PM" src="https://github.com/theochem/DiverseSelector/assets/83951518/e34ae1dd-c7a8-4e5a-9d22-e233f1a591b6">

If others have a different set of tests failing/passing, it would be worth comparing environments to see if problems are arising from that.

**Comment by maximilianvz** [comment]
I previously didn't have Java installed on my computer, which is the reason [test_feature_desc_padelpy_3d](https://github.com/theochem/DiverseSelector/blob/7be2723c51f757912b61e59a08ca6379361751dd/DiverseSelector/test/test_feature.py#LL84C5-L84C33) was failing for me. If anyone else has that problem, they should simply [download Java](https://www.java.com/en/).

**Comment by maximilianvz** [comment]
A similar problem as per my last comment was causing [test_feature_desc_rdkit_frag](https://github.com/theochem/DiverseSelector/blob/7be2723c51f757912b61e59a08ca6379361751dd/DiverseSelector/test/test_feature.py#L143) to fail. The generated descriptor (`df_rdkit_frag_desc`) contains a descriptor variable, `NumHDonors`, that doesn't appear in the reference descriptor (`df_rdkit_desc_exp`). To make this test pass, I prevented the `NumHDonors` descriptor from being calculated in [rdkit_frag_desc](https://github.com/theochem/DiverseSelector/blob/7be2723c51f757912b61e59a08ca6379361751dd/DiverseSelector/features.py#L213) (see lines 227 and 233):

<img width="853" alt="Screenshot 2023-06-12 at 11 19 11 AM" src="https://github.com/theochem/DiverseSelector/assets/83951518/672ca439-faab-4a0a-8929-460d771d2974">

Once again, I am not a big fan of having to delete descriptor variables in order to make these tests pass, so I would appreciate someone else weighing in here.

**Comment by FanwangM** [comment]
I cannot remember how I generated the data for `df_rdkit_desc_exp`, but I think it's sensible to regenerate the data from another way, say without using our script here. This might help fix the problem here.

**Comment by FarnazH** [comment]
@maximilianvz thanks for your thorough inspection. I have made a separate branch for this issue (which is linked to the issue), called `126-features-module-fix-failed-tests-and-improve-codecoverage`. Please push all the fixes you have made (including comments in the code) to this branch.

Based on our discussion, the `molecules` module is moved in 6db0f8e7c9ec3c2fbfded45d8428a62227672882. We will include notebook examples to show how our package can be used in combination with other libraries.

**Comment by maximilianvz** [comment]
@FarnazH, I've pushed all of my changes to that branch now. As of now, all but four of the tests are passing:

<img width="1680" alt="Screenshot 2023-10-13 at 6 22 50 PM" src="https://github.com/theochem/DiverseSelector/assets/83951518/092a46e3-b22e-4c22-a42f-b415054b931c">

I don't think I really ever took a look at fixing those tests which are still failing, but is there any point in me doing that anymore?

**Comment by FarnazH** [comment]
@maximilianvz, no need to fix the remaining failed tests.
